/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Attractions: typeof import('./src/components/Attractions.vue')['default']
    Blog: typeof import('./src/components/Blog.vue')['default']
    Booking: typeof import('./src/components/Booking.vue')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    Events: typeof import('./src/components/Events.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Guides: typeof import('./src/components/Guides.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Packages: typeof import('./src/components/Packages.vue')['default']
    Restaurants: typeof import('./src/components/Restaurants.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shopping: typeof import('./src/components/Shopping.vue')['default']
    Transport: typeof import('./src/components/Transport.vue')['default']
  }
}
